# Generated by Django 3.2.2 on 2021-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('name', models.CharField(default='adminTest', max_length=100)),
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture_url', models.URLField()),
            ],
        ),
    ]
