# Generated by Django 3.2.2 on 2021-05-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('advId', models.IntegerField()),
                ('bookingDateTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='advisor',
            name='picture_url',
            field=models.URLField(max_length=255),
        ),
    ]
